from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from app.core.database import get_db
from app.core.security import get_current_user
from app.models.user import User, ChatMessage
from app.schemas.schemas import ChatMessageIn, ChatMessageOut

router = APIRouter(prefix="/api/chat", tags=["AI Chat"])

SYSTEM_PROMPT = """You are an English language tutor AI. 
When the user writes in English:
1. Identify and correct grammar/spelling errors clearly.
2. Suggest a better, more natural version of their sentence.
3. Briefly explain why the correction is needed.
4. Keep your tone encouraging and friendly.
Format corrections like: ❌ [original] → ✅ [corrected]
"""


@router.get("/history", response_model=list[ChatMessageOut])
def get_history(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    messages = (
        db.query(ChatMessage)
        .filter(ChatMessage.user_id == current_user.id)
        .order_by(ChatMessage.created_at)
        .limit(100)
        .all()
    )
    return messages


@router.post("/send", response_model=ChatMessageOut)
def send_message(
    payload: ChatMessageIn,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Save user message. AI response is generated by the frontend calling
    the /chat/ai-response endpoint or via a real LLM integration.
    This endpoint handles persistence.
    """
    msg = ChatMessage(user_id=current_user.id, role="user", content=payload.content)
    db.add(msg)
    db.commit()
    db.refresh(msg)
    return msg


@router.post("/ai-response", response_model=ChatMessageOut)
def save_ai_response(
    payload: ChatMessageIn,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Save the AI assistant's response to the DB."""
    msg = ChatMessage(user_id=current_user.id, role="assistant", content=payload.content)
    db.add(msg)
    db.commit()
    db.refresh(msg)
    return msg


@router.get("/system-prompt")
def get_system_prompt(_: User = Depends(get_current_user)):
    """Return the system prompt for frontend LLM calls."""
    return {"system_prompt": SYSTEM_PROMPT}


@router.delete("/history", status_code=204)
def clear_history(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    db.query(ChatMessage).filter(ChatMessage.user_id == current_user.id).delete()
    db.commit()
